// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type User struct {
	ID             string    `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
}

type UserRelateUrl struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	ShortUrl  string    `json:"short_url"`
	OriginUrl string    `json:"origin_url"`
	Status    int32     `json:"status"`
	ExpireAt  time.Time `json:"expire_at"`
	CreatedAt time.Time `json:"created_at"`
}
