// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	CreateUserUrl(ctx context.Context, arg *CreateUserUrlParams) (*UserRelateUrl, error)
	DeleteUser(ctx context.Context, id string) error
	GetUser(ctx context.Context, id string) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByName(ctx context.Context, username string) (*User, error)
	ListUrlByUser(ctx context.Context, userID string) ([]*UserRelateUrl, error)
	ListUsers(ctx context.Context, arg *ListUsersParams) ([]*User, error)
	UpdateStatus(ctx context.Context, arg *UpdateStatusParams) (*UserRelateUrl, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
